extends:
  - react-app
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  react/jsx-curly-spacing:
    - error
    - when: always
      attributes: true
      children: true
      spacing:
        objectLiterals: never
  react/jsx-tag-spacing:
    - error
    - beforeSelfClosing: always
      closingSlash: never
      afterOpening: never
      beforeClosing: never
