default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  migrations_paths: db/migrate/primary

development:
  primary:
    <<: *default
    url: <%= ENV['DEV_DATABASE_URL'] %>

test:
  primary:
    <<: *default
    url: <%= ENV['PRIMARY_TEST_DATABASE_URL'] %>
  secondary:
    <<: *default
    migrations_paths: db/migrate/secondary
    url: <%= ENV['SECONDARY_TEST_DATABASE_URL'] %>

production: &production
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *production
