source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 6.0.1'

gem 'activerecord-import'
gem 'activestorage-database-service', github: 'TitovDigital/activestorage-database-service'
gem 'apollo_upload_server', '2.0.0'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.3.2', require: false
gem 'graphql-batch', '~> 0.3.10'
gem 'graphql-errors', '~> 0.3.0'
gem 'graphql', '~> 1.8.13'
gem 'jwt', '~> 2.1.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.12.0'
gem 'rails-i18n'
gem 'redis-rails'
gem 'roo', '~> 2.8.0'
gem 'sentry-raven', '~> 2.8.0'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sucker_punch', '~> 2.0'


group :development do
  gem 'guard-cucumber'
  gem 'guard-rspec'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubycritic', require: false
  gem 'spring'
end

group :test do
  gem 'shoulda-matchers', '~> 4.0.0'
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'cucumber'
  gem 'factory_bot_rails', '~> 5.0.0'
  gem 'fuubar'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.8'
end

group :production do
  gem 'google-cloud-storage'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
